table tabConfiguracao
	lineageTag: a464b768-9672-42db-ab77-3315d1236453

	column nomeColuna
		dataType: string
		lineageTag: de1fbfd2-2129-4bcb-99ac-f48ab978249b
		summarizeBy: none
		sourceColumn: nomeColuna

		annotation SummarizationSetBy = Automatic

	column Descricao
		dataType: string
		lineageTag: 83de7fea-7677-4e01-a416-51afba6dfb80
		summarizeBy: none
		sourceColumn: Descricao

		annotation SummarizationSetBy = Automatic

	partition tabConfiguracao = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\samuel\Desktop\CONFIGURACAO.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Planilha1_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"nomeColuna", type text}, {"Descricao", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

